### PR TITLE
Use subtype to set vcoll; add voting date to vote sort; fix console errors in recordfile loading

### LINKED ISSUE #996: Votes need sorting by voting date
Votes should have the option to sort by voting date (992 field):

image

### LINKED ISSUE #1666: Different sort options per collection before/after search
This is strange and unexpected behavior:

When I navigate to the [Speeches results page](https://metadata.un.org/editor/records/bibs/search?subtype=speech), I have the following sort options:

Image

Once I search for something, the sort options change (to what they should be):

Image

The same is happening with the Votes page.

### PR DESCRIPTION
**Pull request by aaronhelton**
Fixes #996
Fixes #1666

### CODE REVIEW

File: dlx_rest/static/js/recordfiles.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ export let recordfilecomponent = {
             required: true
         },
         record_id: {
-            type: String,
+            type: Number,
```
Comment (jbukhari) [inline dlx_rest/static/js/recordfiles.js:8]: Not sure what changed where this doesn't work anymore, since the prop is a string in the working production release

Comment (aaronhelton) [reply dlx_rest/static/js/recordfiles.js:8]: It's not that it doesn't work at all, it's that it throws error messages in the console. This happens in production as well (verified today). This change will fix that issue.
